cvm-version: 0.7.5
cpus: 4
memory: 32768

containers:
  - name: "proxy"
    image: "ghcr.io/tinfoilsh/tinfoil-bucket@sha256:9f85261a4b48d077bffe394eb5316ff5eb0673dc79883fe7fdb3131d856a5e89" # v0.0.2
    env:
      - LISTEN_ADDR: ":8080"
      - CONTROL_PLANE_URL: "https://api.tinfoil.sh"
      - USAGE_REPORTER_ID: "tinfoil-bucket"
    secrets:
      - USAGE_REPORTER_SECRET

  - name: "buckets"
    image: "ghcr.io/tinfoilsh/tinfoil-buckets-sidecar@sha256:a0f5fd6a3dbdb0a95799ae687e127bb544b7998221458ae1face3fc8c3f43f30" # v0.0.5
    env:
      - PORT: "9000"
      - BUCKET: "tinfoil-bucket-273354634536-us-east-2-an"
      - AWS_REGION: "us-east-2"
      - MULTITENANT: "true"
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

shim:
  upstream-port: 8080
  paths:
    - /*
